### PR TITLE
reactStringReplace should take/return ReactNodeArray

### LINKED ISSUE #43: Typescript definitions are wrong (I think)
I think the newly added type definitions are not quite correct (at least my otherwise correctly working code now throws type errors after upgrading).

I do something like:  
`reactStringReplace(<whatever>).filter(part => !!part)`
to drop some empty strings, because they would break some stuff afterwards.

Obviously `reactStringReplace` returns an Array of some Sort
```
  return flatten(source.map(function(x) {
    return isString(x) ? replaceString(x, match, fn) : x;
  }));
```

The return type in the type definitions is set to `JSX.Element` which extends `React.ReactElement`.
So on one hand, this can't be an Array and on the other hand it cannot even be a string.

I suppose the return Type should be at least `JSX.Element[]` or furthermore `(JSX.Element | string)[]` to capture the real return type of `reactStringReplace`.

For simplicity one could use `React.ReactChild[]` since `ReactChild` allows `ReactElement` as well as `string` or `number`. 

Correct me if I'm missing something.
I am willing to submit a pull request regarding this issue, I just wanted to ask first in case I'm wrong.

### PR DESCRIPTION
**Pull request by monsterkrampe**
fixes #43

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,5 +1,9 @@
 declare module 'react-string-replace' {
-  function reactStringReplace(text: React.ReactNode, regex: RegExp, cb: (match: string, index: number) => string | JSX.Element): JSX.Element;
+  function reactStringReplace(
+    text?: string | React.ReactNodeArray,
```
Comment (monsterkrampe) [inline index.d.ts]: Intention is:
Initially you would pass a `string`. Also you can pass the result of of the function again, which would be `React.ReactNodeArray`.

File: index.d.ts [hunk 2]
```diff
@@ -1,5 +1,9 @@
 declare module 'react-string-replace' {
-  function reactStringReplace(text: React.ReactNode, regex: RegExp, cb: (match: string, index: number) => string | JSX.Element): JSX.Element;
+  function reactStringReplace(
+    text?: string | React.ReactNodeArray, 
+    regex?: string | RegExp, 
+    cb?: (match: string, index: number, offset: number) => React.ReactNode
```
Comment (monsterkrampe) [inline index.d.ts]: The callback should return any `ReactNode`, which can also be an array or just a simple string.
Objects are not supported, since you could not use them as an React Element.

File: index.d.ts [hunk 3]
```diff
@@ -1,5 +1,9 @@
...
+  ): React.ReactNodeArray;
```
Comment (monsterkrampe) [inline index.d.ts]: `reactStringReplace` always returns an array.
This array contains `string`s, which are one kind of `ReactNode` and anything thta might come from the callback, i.e. `ReactNode`.
Hence we always end up with an `ReactNodeArray`.

**Comment by monsterkrampe** [comment]
I commented my thoughts at the specific lines.

I would be happy to discuss this with you @iansinnott :)

File: index.d.ts (hunk 2 above)
Comment (iansinnott) [reply index.d.ts]: Sounds reasonable to me. If you're accidentally returning an object you'd want to know

**Comment by iansinnott** [comment]
Are `React.ReactNodeArray` and `React.ReactNode` built in to typescript? Where are they defined?

**Comment by monsterkrampe** [comment]
These are defined in the `react` type definitions just like `JSX.Element` which we had before.

I would suggest adding `react` as a peerDependency anyway, but this depends on how you intend to use `react-string-replace`. Just seeing the code, one could assume that this module can be used for anything, not just react.  
If this is your intention, I would not like to use `React.ReactNode` and so on and I would also not add react as a peerDependency.  
But since I think that it is indeed intended to use this module only in combination with react, I think `react` should be added as a peerDependency, although I'm not sure which version.
(hope this is not too off topic)

Let me know what you think.

**Comment by iansinnott** [comment]
> I think that it is indeed intended to use this module only in combination with react

Yeah exactly, even though the code isn't React-specific in practice I would think everyone's using it with React. So I'm happy with the React-centric type definitions.

Thanks for the clarification about where the definitions come from.
